import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&display=swap"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>
          <a href="https://media.cnn.com/api/v1/images/stellar/prod/221013084107-01-queen-rediscovered-song.jpg?c=16x9&q=h_720,w_1280,c_fill">
            HELENA AND YLVA THE QUEENS!
          </a>
        </h1>
        <Link href={"/muppar"} passHref>
          <Image
            src="/muppar.jpg"
            alt="click"
            width={250}
            height={180}
            priority
          />
        </Link>
        <Link href={"/pockemons"} passHref>
          <Image
            src="/pockball.jpg"
            alt="click"
            width={250}
            height={250}
            priority
          />
        </Link>
        <div></div>
      </main>
    </>
  );
}
